#!/bin/bash
#PBS -S /bin/bash
#PBS -q dev #short, normalq
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:15:00
#PBS -M # you@my.erau.edu 
#PBS -n 
#PBS -N p_test #JOB_NAME
#PBS -d /scratch/khana66a/hpc-python/PS
# PBS <-- This is a comment, note the whitespace

### cd to directory where the job was submitted:
cd "${PBS_O_WORKDIR}"

# load the required environment modules 
#module load openmpi/gcc/64/1.10.3 
module load python/3.9.2

### run the program (on the nodes as provided by PBS):

date
python auc.py 10000 > ${PBS_JOBNAME}_auc.out
date

date
mpirun -n 16 ./code.x > ${PBS_JOBNAME}.out 
date

#date
#mpirun -ppn $PBS_NUM_PPN -f $PBS_NODEFILE -n $PBS_NP ./mpi.x > ${PBS_JOBNAME}_mpi.out
#date
#
#date
#mpirun -ppn $PBS_NUM_PPN -f $PBS_NODEFILE -n $PBS_NP ./hybrid.x > ${PBS_JOBNAME}_hybrid.out
#date

###############################################################################
